"use client";

/**
 * ReportViewer -- renders the HTML report returned by the report service.
 *
 * Uses a sandboxed iframe so the report HTML (which may include styles/scripts
 * generated by Jinja2) cannot affect the parent page.
 *
 * Security: sandbox="allow-same-origin" allows CSS to load but blocks scripts,
 * popups, and form submissions from the report content.
 */

import { ReportStatus } from "@/lib/types";
import styles from "./report.module.css";

interface ReportViewerProps {
  report: ReportStatus;
}

export default function ReportViewer({ report }: ReportViewerProps) {
  if (!report.has_html || !report.report_html) {
    return (
      <div className={styles.noHtml} role="status">
        <p>Report content is not available in HTML format for this entry.</p>
      </div>
    );
  }

  const blob = new Blob([report.report_html], { type: "text/html" });
  const objectUrl = URL.createObjectURL(blob);

  return (
    <div className={styles.viewerWrapper}>
      <div className={styles.viewerMeta}>
        <span className={styles.metaLabel}>NPI</span>
        <span className={styles.metaValue}>{report.npi}</span>
        {report.is_partial && (
          <span className={styles.partialBadge}>Partial Report</span>
        )}
        {report.completed_at && (
          <>
            <span className={styles.metaLabel}>Generated</span>
            <span className={styles.metaValue}>
              {new Date(report.completed_at).toLocaleString()}
            </span>
          </>
        )}
      </div>
      <iframe
        title={`Provider report NPI ${report.npi}`}
        className={styles.reportFrame}
        sandbox="allow-same-origin"
        srcDoc={report.report_html}
        data-testid="report-iframe"
      />
    </div>
  );
}
